FROM n8nio/n8n:2.16.1

ENV N8N_PORT=7860
ENV N8N_PROXY_HOPS=1
ENV N8N_LISTEN_ADDRESS=0.0.0.0
ENV N8N_EDITOR_BASE_URL=https://ltidler-n8n-smart-accountant.hf.space
ENV WEBHOOK_URL=https://ltidler-n8n-smart-accountant.hf.space
ENV N8N_SECURE_COOKIE=false
ENV N8N_EXPERIMENTAL_DISABLE_RATE_LIMITER=true
ENV DB_POSTGRESDB_CONNECTION_TIMEOUT=60000
ENV DB_POSTGRESDB_POOL_SIZE=5

ENTRYPOINT ["n8n"]
CMD ["start"]
